// ============================================
// SORIVA HEALTH - CONSTANTS (LEGALLY BULLETPROOF v2.0)
// Path: src/modules/health/health.constants.ts
// ============================================
// 🛡️ This file contains comprehensive legal protection
// including response sanitization, blocked patterns,
// and behaviour-level enforcement for medical AI safety.
// ============================================

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// FILE UPLOAD LIMITS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const FILE_LIMITS = {
  MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB
  ALLOWED_MIME_TYPES: [
    'image/jpeg',
    'image/jpg',
    'image/png',
    'image/webp',
    'application/pdf',
  ],
  ALLOWED_EXTENSIONS: ['.jpg', '.jpeg', '.png', '.webp', '.pdf'],
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// FILE MAGIC BYTES (Basic Malware/Validation Check)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const FILE_MAGIC_BYTES: Record<string, number[]> = {
  'image/jpeg': [0xff, 0xd8, 0xff],
  'image/jpg': [0xff, 0xd8, 0xff],
  'image/png': [0x89, 0x50, 0x4e, 0x47],
  'image/webp': [0x52, 0x49, 0x46, 0x46], // RIFF
  'application/pdf': [0x25, 0x50, 0x44, 0x46], // %PDF
};

/**
 * Validate file by checking magic bytes
 * Returns true if file matches expected type
 */
export const validateFileMagicBytes = (
  buffer: Buffer,
  mimeType: string
): boolean => {
  const expectedBytes = FILE_MAGIC_BYTES[mimeType];
  if (!expectedBytes) return false;

  for (let i = 0; i < expectedBytes.length; i++) {
    if (buffer[i] !== expectedBytes[i]) {
      return false;
    }
  }
  return true;
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 🛡️ LEGAL DISCLAIMERS (Multi-Level Protection)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const HEALTH_DISCLAIMER = {
  // Short disclaimer for inline use
  SHORT:
    'This is AI-generated health information, not medical advice. Please consult a qualified healthcare professional.',

  // Full disclaimer for reports
  FULL: `⚠️ IMPORTANT DISCLAIMER:
This report is generated by Soriva Health AI and is strictly for INFORMATIONAL and EDUCATIONAL purposes only.

• This is NOT a medical diagnosis
• This is NOT treatment advice
• This does NOT replace professional medical consultation
• This should NOT be used to make medical decisions

Always consult a qualified healthcare provider (MBBS/MD/Specialist) for:
- Interpreting your test results
- Diagnosis of any medical condition
- Treatment recommendations
- Medication decisions

Soriva AI analyzes patterns in your reports but cannot and does not provide medical diagnosis or treatment advice.`,

  // Emergency warning
  EMERGENCY: `🚨 MEDICAL EMERGENCY WARNING:
If you are experiencing any of the following, STOP reading and seek immediate medical help:
• Chest pain or difficulty breathing
• Sudden severe headache
• Loss of consciousness
• Severe bleeding
• Signs of stroke (face drooping, arm weakness, speech difficulty)

Emergency Numbers:
• India: 108 / 112
• Ambulance: 102
• USA: 911`,

  // Chat disclaimer (shown at start of every health chat)
  CHAT: `🏥 Soriva Health Assistant

I can help you understand your health reports and answer general health questions.

⚠️ Important:
• I provide INFORMATION only, not medical advice
• I cannot diagnose conditions or prescribe treatments
• Always verify information with your doctor
• For emergencies, call 108/112 immediately

How can I help you today?`,

  // Analysis disclaimer (shown with every report analysis)
  ANALYSIS: `⚠️ AI ANALYSIS DISCLAIMER:
This AI-powered analysis is for informational purposes only.

• Reference ranges may vary between laboratories
• Individual factors affect normal values (age, gender, medications, etc.)
• Only a qualified doctor can interpret results in your clinical context
• Do NOT start, stop, or change any medication based on this analysis

Consult your healthcare provider for proper interpretation and advice.`,

  // PDF/Doctor Summary disclaimer
  PDF_HEADER: `SORIVA HEALTH - AI GENERATED REPORT
FOR INFORMATIONAL PURPOSES ONLY - NOT A MEDICAL DOCUMENT
This report is generated by artificial intelligence and requires verification by a qualified healthcare professional.`,

  PDF_FOOTER: `This document is AI-generated and does not constitute medical advice, diagnosis, or treatment recommendation.
Patient should consult a licensed healthcare provider for all medical decisions.
Generated by Soriva Health AI | www.soriva.com | Not for clinical use without physician review.`,

  // Terms user must accept
  USER_ACKNOWLEDGMENT: `By using Soriva Health, I acknowledge and agree that:

1. Soriva Health is an AI-powered informational tool, NOT a medical service
2. All analysis and information provided is for educational purposes only
3. I will NOT use this service as a substitute for professional medical advice
4. I will consult a qualified healthcare provider for any medical decisions
5. Soriva and its creators are NOT liable for any decisions made based on this information
6. I understand AI can make errors and will verify all information with my doctor
7. In case of medical emergency, I will contact emergency services immediately

I accept these terms and understand the limitations of AI health analysis.`,
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 🚫 BLOCKED CONTENT PATTERNS (Behaviour-Level Enforcement)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/**
 * These patterns are BLOCKED from AI responses.
 * If detected, they will be replaced with safe alternatives.
 */

// 🔴 DIAGNOSIS PATTERNS - AI should NEVER diagnose
export const BLOCKED_DIAGNOSIS_PATTERNS: RegExp[] = [
  // Direct diagnosis statements
  /you\s+(have|are\s+suffering\s+from|are\s+diagnosed\s+with|definitely\s+have)\s+\w+/gi,
  /this\s+(confirms|indicates|shows|proves)\s+(you\s+have|that\s+you\s+have|diagnosis\s+of)/gi,
  /diagnosis[:\s]+\w+/gi,
  /you\s+are\s+(diabetic|anemic|hypertensive|hyperthyroid|hypothyroid)/gi,
  /confirmed\s+(diabetes|anemia|thyroid|cancer|tumor|disease)/gi,

  // Disease declarations
  /you\s+(definitely|clearly|certainly|surely)\s+have/gi,
  /this\s+is\s+(definitely|clearly|certainly)\s+(diabetes|cancer|anemia|thyroid)/gi,
  /no\s+doubt\s+(you\s+have|this\s+is|about)/gi,

  // Certainty statements about conditions
  /100%\s+(sure|certain|confirmed)/gi,
  /without\s+(a\s+)?doubt/gi,
  /conclusive(ly)?\s+(shows?|proves?|indicates?)/gi,
];

// 🔴 MEDICATION PATTERNS - AI should NEVER prescribe
export const BLOCKED_MEDICATION_PATTERNS: RegExp[] = [
  // Direct prescription
  /take\s+\d+\s*(mg|ml|mcg|tablet|capsule|pill)/gi,
  /dosage[:\s]+\d+\s*(mg|ml|mcg)/gi,
  /prescri(be|ption|bed)[:\s]+/gi,
  /you\s+(should|must|need\s+to)\s+take\s+\w+\s+\d+/gi,

  // Specific medication recommendations
  /start\s+(taking|with)\s+\w+(in|ol|ide|ate|ine)\s+\d+/gi,
  /increase\s+(your\s+)?(dose|dosage|medication)/gi,
  /decrease\s+(your\s+)?(dose|dosage|medication)/gi,
  /stop\s+taking\s+\w+/gi,
  /switch\s+(to|from)\s+\w+/gi,

  // Dosage patterns
  /\d+\s*(mg|ml|mcg|g|iu)\s*(once|twice|thrice|daily|weekly|monthly)/gi,
  /\d+\s*times?\s*(a|per)\s*(day|week|month)/gi,
  /(morning|evening|night|before\s+meal|after\s+meal)\s*[:\-]?\s*\d+\s*(mg|tablet)/gi,

  // OTC medication suggestions
  /(take|try|use)\s+(paracetamol|aspirin|ibuprofen|crocin|dolo|combiflam)/gi,
];

// 🔴 COMMON MEDICINE NAMES (Blocked from responses)
export const BLOCKED_MEDICINE_NAMES: string[] = [
  // Diabetes medications
  'metformin', 'glimepiride', 'gliclazide', 'sitagliptin', 'vildagliptin',
  'pioglitazone', 'insulin', 'glucophage', 'januvia', 'galvus',
  
  // Blood pressure medications
  'amlodipine', 'telmisartan', 'losartan', 'ramipril', 'enalapril',
  'atenolol', 'metoprolol', 'hydrochlorothiazide', 'furosemide',
  
  // Cholesterol medications
  'atorvastatin', 'rosuvastatin', 'simvastatin', 'fenofibrate', 'lipitor',
  
  // Thyroid medications
  'levothyroxine', 'eltroxin', 'thyronorm', 'thyrox',
  
  // Pain/Fever medications
  'paracetamol', 'ibuprofen', 'aspirin', 'diclofenac', 'aceclofenac',
  'crocin', 'dolo', 'combiflam', 'brufen', 'voveran',
  
  // Antibiotics
  'amoxicillin', 'azithromycin', 'ciprofloxacin', 'levofloxacin',
  'cefixime', 'doxycycline', 'metronidazole', 'augmentin',
  
  // Antacids/GI medications
  'omeprazole', 'pantoprazole', 'ranitidine', 'domperidone', 'ondansetron',
  
  // Supplements (when used as treatment)
  'vitamin d3', 'calcirol', 'shelcal', 'b12 injection', 'folic acid',
  
  // Psychiatric medications
  'alprazolam', 'clonazepam', 'diazepam', 'escitalopram', 'sertraline',
  'fluoxetine', 'olanzapine', 'risperidone',
  
  // Cardiac medications
  'clopidogrel', 'warfarin', 'rivaroxaban', 'digoxin', 'nitroglycerine',
  
  // Steroids
  'prednisolone', 'dexamethasone', 'hydrocortisone', 'betamethasone',
  
  // Allergy medications
  'cetirizine', 'levocetirizine', 'fexofenadine', 'montelukast',
];

// 🔴 DANGEROUS ADVICE PATTERNS
export const BLOCKED_DANGEROUS_PATTERNS: RegExp[] = [
  // Dangerous health advice
  /stop\s+(your\s+)?(medication|medicine|treatment|therapy)/gi,
  /don'?t\s+(see|visit|consult|go\s+to)\s+(a\s+)?(doctor|physician|hospital)/gi,
  /no\s+need\s+(to|for)\s+(see|visit|consult)\s+(a\s+)?doctor/gi,
  /you\s+don'?t\s+need\s+(a\s+)?doctor/gi,
  /ignore\s+(this|these|the)\s+(symptoms?|results?|values?)/gi,
  /nothing\s+to\s+worry\s+about/gi,
  /perfectly\s+(fine|normal|healthy)/gi,

  // Alternative medicine as treatment
  /cure\s+(diabetes|cancer|thyroid|hypertension)\s+(with|using|by)/gi,
  /home\s+remedy\s+(for|to\s+cure|to\s+treat)/gi,
  /(ayurvedic|homeopathic|natural)\s+(cure|treatment)\s+for/gi,

  // Delay seeking care
  /wait\s+(and\s+)?(see|watch)/gi,
  /give\s+it\s+(some\s+)?time/gi,
  /no\s+(immediate\s+)?action\s+(needed|required)/gi,
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 🇮🇳 HINDI/HINGLISH BLOCKED PATTERNS (v1.1)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const BLOCKED_HINDI_PATTERNS: RegExp[] = [
  // Hindi diagnosis patterns
  /aapko\s+(diabetes|sugar|thyroid|bp|cancer)\s+hai/gi,
  /tumhe\s+(diabetes|sugar|thyroid|bp|cancer)\s+hai/gi,
  /ye\s+(diabetes|sugar|thyroid|bp)\s+(hai|he)/gi,
  /pakka\s+(diabetes|sugar|cancer|thyroid)/gi,
  /confirm\s+(diabetes|sugar|cancer|thyroid)/gi,
  
  // Hindi medication patterns
  /ye\s+(dawa|dawai|tablet|goli|medicine)\s+(lo|lena|khao|khana)/gi,
  /is\s+(tablet|goli|dawai)\s+se\s+(theek|thik|sahi)/gi,
  /(subah|sham|raat)\s+ko\s+\d+\s*(mg|tablet|goli)/gi,
  /din\s+me\s+\d+\s+(baar|time)\s+(lo|lena|khao)/gi,
  /\d+\s*(goli|tablet)\s+(roz|daily|rozana)/gi,
  
  // Hindi dangerous advice
  /doctor\s+(ki\s+)?zaroorat\s+nahi/gi,
  /doctor\s+ke\s+paas\s+(mat\s+)?jana/gi,
  /tension\s+(mat\s+)?lo/gi,
  /kuch\s+nahi\s+(hoga|hua)/gi,
  /fikar\s+(mat\s+)?karo/gi,
  /chinta\s+(mat\s+)?karo/gi,
  /ghar\s+pe\s+(ilaj|treatment)/gi,
  /desi\s+(ilaj|nuskha|upay)/gi,
  
  // Hinglish certainty patterns
  /definitely\s+(sugar|diabetes|thyroid)\s+hai/gi,
  /100%\s+(sugar|diabetes|cancer)/gi,
  /pakka\s+wala\s+(disease|bimari)/gi,
];

// 🇮🇳 HINDI MEDICINE NAMES
export const BLOCKED_HINDI_MEDICINE_TERMS: string[] = [
  // Common Hindi terms for medicines
  'dawa', 'dawai', 'goli', 'tablet', 'capsule', 'syrup', 'injection',
  'insulin ka injection', 'sugar ki goli', 'bp ki dawa', 'thyroid ki tablet',
  
  // Branded medicines in Hindi context
  'crocin khao', 'dolo lo', 'combiflam', 'saridon',
];

// 🇮🇳 SAFE HINDI REPLACEMENTS
export const SAFE_HINDI_REPLACEMENTS: Record<string, string> = {
  'aapko diabetes hai': 'aapke sugar levels check karne chahiye doctor se',
  'tumhe sugar hai': 'glucose levels elevated hain, doctor se milein',
  'ye dawa lo': 'doctor se consult karein medication ke baare mein',
  'is tablet se theek': 'doctor aapko sahi treatment batayenge',
  'doctor ki zaroorat nahi': 'doctor se zaroor milein confirmation ke liye',
  'tension mat lo': 'doctor se consult karna important hai',
  'kuch nahi hoga': 'professional evaluation zaroori hai',
  'ghar pe ilaj': 'qualified doctor ka consultation zaroori hai',
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ✅ SAFE REPLACEMENT PHRASES
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const SAFE_REPLACEMENTS: Record<string, string> = {
  // Diagnosis replacements
  'you have diabetes':
    'your glucose levels appear elevated. Please consult a doctor for proper evaluation',
  'you have anemia':
    'your hemoglobin levels appear low. Please consult a doctor for proper evaluation',
  'you have thyroid':
    'your thyroid markers show variations. Please consult an endocrinologist for evaluation',
  'you are diabetic':
    'your glucose markers need medical evaluation. Please consult a doctor',
  'you are anemic':
    'your blood parameters suggest you should consult a doctor for evaluation',
  'this confirms':
    'these values may suggest. However, only a doctor can confirm',
  'diagnosis:':
    'Observation (requires doctor verification):',

  // Medication replacements
  'take metformin':
    'your doctor may discuss glucose management options with you',
  'take insulin':
    'your doctor may discuss insulin therapy if appropriate for your case',
  'you should take':
    'your doctor may recommend',
  'you need to take':
    'you should discuss with your doctor about',
  'start taking':
    'consult your doctor about starting',
  'stop taking':
    'discuss with your doctor before making any changes to',

  // Certainty replacements
  'definitely have':
    'may have (requires doctor confirmation)',
  'clearly shows':
    'may suggest (requires professional interpretation)',
  'no doubt':
    'based on these values, but confirmation requires medical evaluation',
  '100% sure':
    'suggestive, but requires doctor verification',

  // Dangerous advice replacements
  'nothing to worry about':
    'discuss these results with your doctor for proper guidance',
  'perfectly normal':
    'within reference range, but consult your doctor for personalized interpretation',
  "don't need a doctor":
    'should still discuss with a healthcare provider for confirmation',
  'no need to see a doctor':
    'recommend confirming with a healthcare provider',
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 🔧 RESPONSE SANITIZER CLASS (v1.1 - Enhanced)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export interface SanitizationResult {
  originalText: string;
  sanitizedText: string;
  wasModified: boolean;
  wasBlocked: boolean; // NEW: Complete block flag
  blockedPatterns: string[];
  blockedMedicines: string[];
  replacementsMade: string[];
  riskLevel: 'SAFE' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  timestamp: Date;
  blockReason?: string; // NEW: Why it was blocked
}

// 🚨 CRITICAL BLOCK MESSAGE - When response is too risky to show
export const CRITICAL_BLOCK_MESSAGE = `🚨 Safety Notice

This health query requires direct consultation with a qualified healthcare professional.

Soriva Health cannot safely provide information for this specific request because it may require:
• Professional medical evaluation
• Physical examination
• Access to your complete medical history
• Clinical judgment that only a doctor can provide

**What you should do:**
1. Contact your doctor or visit a clinic
2. For emergencies, call 108/112 immediately
3. Bring your reports for professional interpretation

We prioritize your safety above all else.

— Soriva Health Team`;

// 🚨 HINDI CRITICAL BLOCK MESSAGE
export const CRITICAL_BLOCK_MESSAGE_HINDI = `🚨 Safety Notice

Is sawaal ka jawab dena Soriva ke liye safe nahi hai.

Aapko doctor se milna chahiye kyunki:
• Professional medical evaluation zaroori hai
• Physical examination ki zaroorat ho sakti hai
• Aapki complete medical history dekhni padegi
• Clinical judgment sirf doctor de sakte hain

**Aap ye karein:**
1. Apne doctor se milein ya clinic jaayein
2. Emergency mein 108/112 call karein
3. Apni reports doctor ko dikhayein

Aapki safety humari pehli priority hai.

— Soriva Health Team`;

export class HealthResponseSanitizer {
  /**
   * Main sanitization method - call this on ALL AI responses
   * v1.3: Fixed double-scan bug, added injection protection
   */
  static sanitize(text: string, language: 'en' | 'hi' = 'en'): SanitizationResult {
    const result: SanitizationResult = {
      originalText: text,
      sanitizedText: text,
      wasModified: false,
      wasBlocked: false,
      blockedPatterns: [],
      blockedMedicines: [],
      replacementsMade: [],
      riskLevel: 'SAFE',
      timestamp: new Date(),
    };

    let processedText = text;
    // 🔧 FIX: Re-normalize after EACH modification to prevent double-scan bug
    let normalizedText = text.toLowerCase();

    // 🚀 Step 1: Check diagnosis patterns (compiled)
    COMPILED_PATTERNS.DIAGNOSIS.lastIndex = 0;
    if (COMPILED_PATTERNS.DIAGNOSIS.test(normalizedText)) {
      COMPILED_PATTERNS.DIAGNOSIS.lastIndex = 0;
      const matches = normalizedText.match(COMPILED_PATTERNS.DIAGNOSIS);
      if (matches) {
        result.blockedPatterns.push(...matches.map(m => `DIAGNOSIS: ${m}`));
        result.riskLevel = this.escalateRisk(result.riskLevel, 'HIGH');
      }
      processedText = processedText.replace(
        COMPILED_PATTERNS.DIAGNOSIS,
        '[This observation requires doctor verification]'
      );
      result.wasModified = true;
      // 🔧 FIX: Re-normalize for next check
      normalizedText = processedText.toLowerCase();
    }

    // 🚀 Step 2: Check medication patterns (compiled)
    COMPILED_PATTERNS.MEDICATION.lastIndex = 0;
    if (COMPILED_PATTERNS.MEDICATION.test(normalizedText)) {
      COMPILED_PATTERNS.MEDICATION.lastIndex = 0;
      const matches = normalizedText.match(COMPILED_PATTERNS.MEDICATION);
      if (matches) {
        result.blockedPatterns.push(...matches.map(m => `MEDICATION: ${m}`));
        result.riskLevel = this.escalateRisk(result.riskLevel, 'CRITICAL');
      }
      processedText = processedText.replace(
        COMPILED_PATTERNS.MEDICATION,
        '[Please consult your doctor for medication advice]'
      );
      result.wasModified = true;
      // 🔧 FIX: Re-normalize for next check
      normalizedText = processedText.toLowerCase();
    }

    // 🚀 Step 3: Check dangerous patterns (compiled)
    COMPILED_PATTERNS.DANGEROUS.lastIndex = 0;
    if (COMPILED_PATTERNS.DANGEROUS.test(normalizedText)) {
      COMPILED_PATTERNS.DANGEROUS.lastIndex = 0;
      const matches = normalizedText.match(COMPILED_PATTERNS.DANGEROUS);
      if (matches) {
        result.blockedPatterns.push(...matches.map(m => `DANGEROUS: ${m}`));
        result.riskLevel = this.escalateRisk(result.riskLevel, 'CRITICAL');
      }
      processedText = processedText.replace(
        COMPILED_PATTERNS.DANGEROUS,
        '[Please consult a healthcare professional]'
      );
      result.wasModified = true;
      // 🔧 FIX: Re-normalize for next check
      normalizedText = processedText.toLowerCase();
    }

    // 🚀 Step 4: Check Hindi patterns (compiled)
    COMPILED_PATTERNS.HINDI.lastIndex = 0;
    if (COMPILED_PATTERNS.HINDI.test(normalizedText)) {
      COMPILED_PATTERNS.HINDI.lastIndex = 0;
      const matches = normalizedText.match(COMPILED_PATTERNS.HINDI);
      if (matches) {
        result.blockedPatterns.push(...matches.map(m => `HINDI: ${m}`));
        result.riskLevel = this.escalateRisk(result.riskLevel, 'HIGH');
      }
      processedText = processedText.replace(
        COMPILED_PATTERNS.HINDI,
        '[Doctor se consult karein]'
      );
      result.wasModified = true;
      // 🔧 FIX: Re-normalize for next check
      normalizedText = processedText.toLowerCase();
    }

    // 🚀 Step 5: Check medicine names (compiled master regex)
    COMPILED_MEDICINE_REGEX.lastIndex = 0;
    if (COMPILED_MEDICINE_REGEX.test(normalizedText)) {
      COMPILED_MEDICINE_REGEX.lastIndex = 0;
      const matches = normalizedText.match(COMPILED_MEDICINE_REGEX);
      if (matches) {
        result.blockedMedicines.push(...matches);
        result.riskLevel = this.escalateRisk(result.riskLevel, 'HIGH');
      }
      processedText = processedText.replace(
        COMPILED_MEDICINE_REGEX,
        '[medication - consult doctor]'
      );
      result.wasModified = true;
      // 🔧 FIX: Re-normalize for next check
      normalizedText = processedText.toLowerCase();
    }

    // 🔐 Step 6: Fuzzy medicine detection (anti-evasion)
    const fuzzyMatches = detectFuzzyMedicines(normalizedText);
    if (fuzzyMatches.length > 0) {
      for (const match of fuzzyMatches) {
        result.blockedMedicines.push(`${match.medicine} (fuzzy: ${match.matched})`);
        result.riskLevel = this.escalateRisk(result.riskLevel, 'HIGH');
        
        // Replace the evaded text (escape for safety)
        const evasionRegex = new RegExp(
          escapeRegex(match.matched),
          'gi'
        );
        processedText = processedText.replace(
          evasionRegex,
          '[medication - consult doctor]'
        );
        result.wasModified = true;
      }
      // 🔧 FIX: Re-normalize after fuzzy replacements
      normalizedText = processedText.toLowerCase();
    }

    // Step 7: Apply safe replacements (English)
    for (const [unsafe, safe] of Object.entries(SAFE_REPLACEMENTS)) {
      const regex = new RegExp(escapeRegex(unsafe), 'gi');
      if (regex.test(normalizedText)) {
        result.replacementsMade.push(`"${unsafe}" → "${safe}"`);
        processedText = processedText.replace(regex, safe);
        result.wasModified = true;
      }
    }
    // 🔧 FIX: Re-normalize after safe replacements
    if (result.wasModified) {
      normalizedText = processedText.toLowerCase();
    }

    // Step 8: Apply Hindi safe replacements
    for (const [unsafe, safe] of Object.entries(SAFE_HINDI_REPLACEMENTS)) {
      const regex = new RegExp(escapeRegex(unsafe), 'gi');
      if (regex.test(normalizedText)) {
        result.replacementsMade.push(`"${unsafe}" → "${safe}"`);
        processedText = processedText.replace(regex, safe);
        result.wasModified = true;
      }
    }

    // 🚨 Step 9: CRITICAL BLOCK MODE
    if (result.riskLevel === 'CRITICAL') {
      result.wasBlocked = true;
      result.blockReason = `Critical risk detected: ${result.blockedPatterns.slice(0, 3).join(', ')}`;
      result.sanitizedText = language === 'hi' 
        ? CRITICAL_BLOCK_MESSAGE_HINDI 
        : CRITICAL_BLOCK_MESSAGE;
      return result;
    }

    // Step 10: Add mandatory disclaimer if response was modified (non-critical)
    if (result.wasModified && result.riskLevel !== 'SAFE') {
      processedText += '\n\n' + HEALTH_DISCLAIMER.SHORT;
    }

    result.sanitizedText = processedText;
    return result;
  }

  /**
   * Quick check if text contains any blocked content
   * v1.2: Uses compiled patterns for better performance
   */
  static containsBlockedContent(text: string): boolean {
    const normalizedText = text.toLowerCase();

    // Check compiled patterns (fast)
    COMPILED_PATTERNS.DIAGNOSIS.lastIndex = 0;
    if (COMPILED_PATTERNS.DIAGNOSIS.test(normalizedText)) return true;

    COMPILED_PATTERNS.MEDICATION.lastIndex = 0;
    if (COMPILED_PATTERNS.MEDICATION.test(normalizedText)) return true;

    COMPILED_PATTERNS.DANGEROUS.lastIndex = 0;
    if (COMPILED_PATTERNS.DANGEROUS.test(normalizedText)) return true;

    COMPILED_PATTERNS.HINDI.lastIndex = 0;
    if (COMPILED_PATTERNS.HINDI.test(normalizedText)) return true;

    // Check compiled medicine regex
    COMPILED_MEDICINE_REGEX.lastIndex = 0;
    if (COMPILED_MEDICINE_REGEX.test(normalizedText)) return true;

    // Check fuzzy matches (slower, but catches evasion)
    const fuzzyMatches = detectFuzzyMedicines(normalizedText);
    if (fuzzyMatches.length > 0) return true;

    return false;
  }

  /**
   * Get list of all blocked items found in text
   * v1.2: Includes fuzzy matches
   */
  static getBlockedItems(text: string): {
    diagnoses: string[];
    medications: string[];
    medicines: string[];
    dangerous: string[];
    hindi: string[];
    fuzzyMatches: Array<{ medicine: string; matched: string; confidence: number }>;
  } {
    const normalizedText = text.toLowerCase();
    const items = {
      diagnoses: [] as string[],
      medications: [] as string[],
      medicines: [] as string[],
      dangerous: [] as string[],
      hindi: [] as string[],
      fuzzyMatches: [] as Array<{ medicine: string; matched: string; confidence: number }>,
    };

    COMPILED_PATTERNS.DIAGNOSIS.lastIndex = 0;
    const diagMatches = normalizedText.match(COMPILED_PATTERNS.DIAGNOSIS);
    if (diagMatches) items.diagnoses.push(...diagMatches);

    COMPILED_PATTERNS.MEDICATION.lastIndex = 0;
    const medMatches = normalizedText.match(COMPILED_PATTERNS.MEDICATION);
    if (medMatches) items.medications.push(...medMatches);

    COMPILED_PATTERNS.DANGEROUS.lastIndex = 0;
    const dangMatches = normalizedText.match(COMPILED_PATTERNS.DANGEROUS);
    if (dangMatches) items.dangerous.push(...dangMatches);

    COMPILED_PATTERNS.HINDI.lastIndex = 0;
    const hindiMatches = normalizedText.match(COMPILED_PATTERNS.HINDI);
    if (hindiMatches) items.hindi.push(...hindiMatches);

    COMPILED_MEDICINE_REGEX.lastIndex = 0;
    const medicineMatches = normalizedText.match(COMPILED_MEDICINE_REGEX);
    if (medicineMatches) items.medicines.push(...medicineMatches);

    // Fuzzy matches
    const fuzzy = detectFuzzyMedicines(normalizedText);
    items.fuzzyMatches = fuzzy.map(f => ({
      medicine: f.medicine,
      matched: f.matched,
      confidence: f.confidence,
    }));

    return items;
  }

  /**
   * Check if response should be completely blocked
   */
  static shouldBlock(text: string): { block: boolean; reason: string } {
    const result = this.sanitize(text);
    
    if (result.riskLevel === 'CRITICAL') {
      return {
        block: true,
        reason: `Critical content detected: ${result.blockedPatterns.slice(0, 3).join(', ')}`,
      };
    }

    // Additional block conditions
    const blockedItems = this.getBlockedItems(text);
    
    // Block if multiple medication prescriptions detected
    if (blockedItems.medications.length >= 2) {
      return {
        block: true,
        reason: 'Multiple medication prescriptions detected',
      };
    }

    // Block if diagnosis + medication combo
    if (blockedItems.diagnoses.length > 0 && blockedItems.medications.length > 0) {
      return {
        block: true,
        reason: 'Diagnosis with medication recommendation detected',
      };
    }

    // Block if fuzzy medicine evasion detected with high confidence
    const highConfidenceFuzzy = blockedItems.fuzzyMatches.filter(f => f.confidence >= 0.85);
    if (highConfidenceFuzzy.length > 0) {
      return {
        block: true,
        reason: `Medicine name evasion detected: ${highConfidenceFuzzy.map(f => f.medicine).join(', ')}`,
      };
    }

    return { block: false, reason: '' };
  }

  /**
   * Escalate risk level
   */
  private static escalateRisk(
    current: SanitizationResult['riskLevel'],
    newLevel: SanitizationResult['riskLevel']
  ): SanitizationResult['riskLevel'] {
    const levels = ['SAFE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
    const currentIndex = levels.indexOf(current);
    const newIndex = levels.indexOf(newLevel);
    return levels[Math.max(currentIndex, newIndex)] as SanitizationResult['riskLevel'];
  }
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 📝 AI PROMPT TEMPLATES (Legally Safe)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const AI_PROMPTS = {
  // System prompt for health analysis
  ANALYSIS_SYSTEM: `You are Soriva Health AI, an educational health information assistant.

CRITICAL RULES - YOU MUST FOLLOW:
1. NEVER diagnose any medical condition
2. NEVER prescribe or recommend specific medications
3. NEVER mention specific medicine names or dosages
4. NEVER say "you have [disease]" - instead say "values suggest consulting a doctor"
5. NEVER give certainty about medical conditions
6. ALWAYS recommend consulting a healthcare professional
7. ALWAYS include appropriate disclaimers

YOUR ROLE:
- Explain what health markers mean in simple terms
- Identify values outside reference ranges
- Suggest which type of specialist might be relevant
- Provide general health education
- Encourage professional medical consultation

FORBIDDEN PHRASES:
- "You have diabetes/anemia/thyroid disorder"
- "Take [medicine name]"
- "Dosage: X mg"
- "You don't need a doctor"
- "Nothing to worry about"
- "This confirms [diagnosis]"

SAFE PHRASES TO USE:
- "Your values suggest consulting a doctor for evaluation"
- "A healthcare provider can best interpret these results"
- "Consider discussing with an endocrinologist/cardiologist/etc."
- "These markers may need professional attention"
- "Please verify with your doctor"`,

  // System prompt for health chat
  CHAT_SYSTEM: `You are Soriva Health Assistant, providing general health information.

STRICT RULES:
1. You are NOT a doctor and cannot diagnose
2. You CANNOT prescribe medications
3. You CANNOT interpret test results definitively
4. You MUST recommend professional consultation for medical decisions
5. You MUST add disclaimers when discussing health conditions

WHAT YOU CAN DO:
- Explain medical terms in simple language
- Provide general health education
- Suggest questions to ask your doctor
- Explain what different tests measure
- Share publicly available health guidelines

WHAT YOU CANNOT DO:
- Diagnose conditions
- Prescribe treatments
- Recommend specific medications
- Give dosage information
- Discourage seeking medical care

Always end responses about health concerns with:
"Please consult a healthcare professional for personalized medical advice."`,

  // Template for report analysis
  ANALYSIS_TEMPLATE: `Analyze the following health report data and provide:

1. **Summary**: Brief overview of the report
2. **Key Observations**: Values that are outside reference ranges
3. **What This Means**: Simple explanation (not diagnosis)
4. **Suggested Next Steps**: (Always include "consult doctor")
5. **Questions for Your Doctor**: Help user prepare for appointment

REMEMBER: 
- Do NOT diagnose any condition
- Do NOT recommend specific medications
- Do NOT use certainty language ("you have", "definitely", etc.)
- Always recommend professional consultation

Report Data:
{reportData}`,
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// OCR CONFIGURATION
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const OCR_CONFIG = {
  LANGUAGE: 'eng+hin', // English + Hindi
  MIN_CONFIDENCE: 60, // Minimum confidence score
  TIMEOUT: 30000, // 30 seconds
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// AI MODEL CONFIGURATION
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const AI_CONFIG = {
  // Analysis Model (GPT-4o Mini - more accurate for medical)
  ANALYSIS: {
    MODEL: 'gpt-4o-mini',
    MAX_TOKENS: 2000,
    TEMPERATURE: 0.3, // Lower temperature for consistency
  },
  // Chat Model (Kimi K2 - cost effective)
  CHAT: {
    MODEL: 'kimi-k2',
    MAX_TOKENS: 1000,
    TEMPERATURE: 0.7,
  },
  // Fallback Model
  FALLBACK: {
    MODEL: 'gemini-1.5-flash',
    MAX_TOKENS: 1500,
    TEMPERATURE: 0.5,
  },
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// REPORT TYPE LABELS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const REPORT_TYPE_LABELS: Record<string, string> = {
  BLOOD_TEST: 'Blood Test',
  URINE_TEST: 'Urine Test',
  LIPID_PROFILE: 'Lipid Profile',
  LIVER_FUNCTION: 'Liver Function Test',
  KIDNEY_FUNCTION: 'Kidney Function Test',
  THYROID: 'Thyroid Profile',
  DIABETES: 'Diabetes Panel',
  VITAMIN: 'Vitamin Test',
  HORMONE: 'Hormone Panel',
  CARDIAC: 'Cardiac Markers',
  IMAGING: 'Imaging Report',
  OTHER: 'Other',
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// RISK LEVEL CONFIGURATION
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const RISK_LEVELS = {
  NORMAL: { label: 'Within Range', color: '#10B981', priority: 0 },
  LOW: { label: 'Slightly Outside Range', color: '#6EE7B7', priority: 1 },
  MODERATE: { label: 'Needs Attention', color: '#FBBF24', priority: 2 },
  HIGH: { label: 'Consult Doctor Soon', color: '#F97316', priority: 3 },
  CRITICAL: { label: 'Urgent Medical Attention', color: '#EF4444', priority: 4 },
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ORGAN SYSTEM LABELS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const ORGAN_SYSTEM_LABELS: Record<
  string,
  { label: string; icon: string }
> = {
  CARDIOVASCULAR: { label: 'Heart & Blood Vessels', icon: '❤️' },
  RESPIRATORY: { label: 'Lungs & Airways', icon: '🫁' },
  DIGESTIVE: { label: 'Digestive System', icon: '🫃' },
  NERVOUS: { label: 'Brain & Nerves', icon: '🧠' },
  ENDOCRINE: { label: 'Hormones', icon: '⚗️' },
  IMMUNE: { label: 'Immune System', icon: '🛡️' },
  MUSCULOSKELETAL: { label: 'Bones & Muscles', icon: '🦴' },
  URINARY: { label: 'Urinary System', icon: '💧' },
  REPRODUCTIVE: { label: 'Reproductive', icon: '🧬' },
  INTEGUMENTARY: { label: 'Skin & Hair', icon: '🧴' },
  LYMPHATIC: { label: 'Lymphatic', icon: '🔬' },
  HEPATIC: { label: 'Liver', icon: '🫀' },
  RENAL: { label: 'Kidneys', icon: '🫘' },
  HEMATOLOGICAL: { label: 'Blood', icon: '🩸' },
  OTHER: { label: 'Other', icon: '📋' },
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// COMMON BIOMARKER REFERENCE RANGES
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const BIOMARKER_REFERENCES: Record<
  string,
  {
    unit: string;
    male: { min: number; max: number };
    female: { min: number; max: number };
    organ: string;
  }
> = {
  hemoglobin: {
    unit: 'g/dL',
    male: { min: 13.5, max: 17.5 },
    female: { min: 12.0, max: 16.0 },
    organ: 'HEMATOLOGICAL',
  },
  rbc: {
    unit: 'million/µL',
    male: { min: 4.5, max: 5.5 },
    female: { min: 4.0, max: 5.0 },
    organ: 'HEMATOLOGICAL',
  },
  wbc: {
    unit: 'cells/µL',
    male: { min: 4000, max: 11000 },
    female: { min: 4000, max: 11000 },
    organ: 'IMMUNE',
  },
  platelets: {
    unit: 'lakhs/µL',
    male: { min: 1.5, max: 4.0 },
    female: { min: 1.5, max: 4.0 },
    organ: 'HEMATOLOGICAL',
  },
  glucose_fasting: {
    unit: 'mg/dL',
    male: { min: 70, max: 100 },
    female: { min: 70, max: 100 },
    organ: 'ENDOCRINE',
  },
  hba1c: {
    unit: '%',
    male: { min: 4.0, max: 5.6 },
    female: { min: 4.0, max: 5.6 },
    organ: 'ENDOCRINE',
  },
  creatinine: {
    unit: 'mg/dL',
    male: { min: 0.7, max: 1.3 },
    female: { min: 0.6, max: 1.1 },
    organ: 'RENAL',
  },
  urea: {
    unit: 'mg/dL',
    male: { min: 15, max: 40 },
    female: { min: 15, max: 40 },
    organ: 'RENAL',
  },
  sgpt: {
    unit: 'U/L',
    male: { min: 7, max: 56 },
    female: { min: 7, max: 45 },
    organ: 'HEPATIC',
  },
  sgot: {
    unit: 'U/L',
    male: { min: 10, max: 40 },
    female: { min: 9, max: 32 },
    organ: 'HEPATIC',
  },
  cholesterol_total: {
    unit: 'mg/dL',
    male: { min: 0, max: 200 },
    female: { min: 0, max: 200 },
    organ: 'CARDIOVASCULAR',
  },
  hdl: {
    unit: 'mg/dL',
    male: { min: 40, max: 100 },
    female: { min: 50, max: 100 },
    organ: 'CARDIOVASCULAR',
  },
  ldl: {
    unit: 'mg/dL',
    male: { min: 0, max: 100 },
    female: { min: 0, max: 100 },
    organ: 'CARDIOVASCULAR',
  },
  triglycerides: {
    unit: 'mg/dL',
    male: { min: 0, max: 150 },
    female: { min: 0, max: 150 },
    organ: 'CARDIOVASCULAR',
  },
  tsh: {
    unit: 'µIU/mL',
    male: { min: 0.4, max: 4.0 },
    female: { min: 0.4, max: 4.0 },
    organ: 'ENDOCRINE',
  },
  t3: {
    unit: 'ng/dL',
    male: { min: 80, max: 200 },
    female: { min: 80, max: 200 },
    organ: 'ENDOCRINE',
  },
  t4: {
    unit: 'µg/dL',
    male: { min: 5.0, max: 12.0 },
    female: { min: 5.0, max: 12.0 },
    organ: 'ENDOCRINE',
  },
  vitamin_d: {
    unit: 'ng/mL',
    male: { min: 30, max: 100 },
    female: { min: 30, max: 100 },
    organ: 'OTHER',
  },
  vitamin_b12: {
    unit: 'pg/mL',
    male: { min: 200, max: 900 },
    female: { min: 200, max: 900 },
    organ: 'HEMATOLOGICAL',
  },
  iron: {
    unit: 'µg/dL',
    male: { min: 60, max: 170 },
    female: { min: 37, max: 145 },
    organ: 'HEMATOLOGICAL',
  },
  calcium: {
    unit: 'mg/dL',
    male: { min: 8.5, max: 10.5 },
    female: { min: 8.5, max: 10.5 },
    organ: 'MUSCULOSKELETAL',
  },
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// HEALTH SCORE THRESHOLDS (Renamed for legal safety)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const HEALTH_SCORE_THRESHOLDS = {
  EXCELLENT: {
    min: 90,
    max: 100,
    label: 'Most Values in Range',
    color: '#10B981',
  },
  GOOD: {
    min: 75,
    max: 89,
    label: 'Generally in Range',
    color: '#6EE7B7',
  },
  FAIR: {
    min: 60,
    max: 74,
    label: 'Some Values Need Attention',
    color: '#FBBF24',
  },
  POOR: {
    min: 40,
    max: 59,
    label: 'Multiple Values Outside Range',
    color: '#F97316',
  },
  CRITICAL: {
    min: 0,
    max: 39,
    label: 'Requires Urgent Medical Review',
    color: '#EF4444',
  },
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// CLOUDINARY FOLDER
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const CLOUDINARY_FOLDERS = {
  REPORTS: 'soriva/health/reports',
  SUMMARIES: 'soriva/health/summaries',
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// API ROUTES
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const HEALTH_ROUTES = {
  BASE: '/api/v1/health',
  REPORTS: '/reports',
  CHAT: '/chat',
  COMPARE: '/compare',
  SUMMARY: '/summary',
  ALERTS: '/alerts',
  STATS: '/stats',
  USAGE: '/usage',
  SUBSCRIPTION: '/subscription',
  FAMILY: '/family',
  EMERGENCY: '/emergency',
  DOCTORS: '/doctors',
  HOSPITALS: '/hospitals',
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ERROR MESSAGES
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const ERROR_MESSAGES = {
  LIMIT_EXCEEDED:
    'You have reached your plan limit. Please upgrade to continue.',
  FEATURE_NOT_AVAILABLE:
    'This feature is not available on your current plan.',
  REPORT_NOT_FOUND: 'Report not found.',
  INVALID_FILE: 'Invalid file type. Please upload JPG, PNG, or PDF.',
  INVALID_FILE_CONTENT:
    'File content does not match the expected format. Please upload a valid file.',
  FILE_TOO_LARGE: 'File size exceeds 10MB limit.',
  OCR_FAILED: 'Failed to process report. Please try again.',
  ANALYSIS_FAILED: 'Failed to analyze report. Please try again.',
  SUBSCRIPTION_REQUIRED: 'Please subscribe to access this feature.',
  FAMILY_LIMIT_REACHED:
    'Maximum family members limit reached for your plan.',
  UNAUTHORIZED: 'You are not authorized to access this resource.',
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 📊 SANITIZATION AUDIT LOG INTERFACE
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export interface SanitizationAuditLog {
  id: string;
  userId: string;
  sessionId?: string;
  originalContent: string;
  sanitizedContent: string;
  blockedItems: {
    diagnoses: string[];
    medications: string[];
    medicines: string[];
    dangerous: string[];
  };
  riskLevel: string;
  wasBlocked: boolean;
  timestamp: Date;
  endpoint: string;
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 🚀 COMPILED REGEX CACHE (Performance Optimization v1.2)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Instead of 10-15 regex loops, we compile into master patterns
// This reduces CPU load by ~70% on high traffic

// Helper to safely combine regex patterns
const combinePatterns = (patterns: RegExp[]): RegExp => {
  const sources = patterns.map(p => p.source);
  return new RegExp(sources.join('|'), 'gi');
};

// 🔐 SECURITY: Escape special regex characters to prevent injection
// Critical if medicine list is ever loaded from DB
const escapeRegex = (s: string): string =>
  s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// 🔴 MASTER COMPILED PATTERNS (Single regex check instead of loops)
export const COMPILED_PATTERNS = {
  // All diagnosis patterns combined
  DIAGNOSIS: combinePatterns([
    /you\s+(have|are\s+suffering\s+from|are\s+diagnosed\s+with|definitely\s+have)\s+\w+/,
    /this\s+(confirms|indicates|shows|proves)\s+(you\s+have|that\s+you\s+have|diagnosis\s+of)/,
    /diagnosis[:\s]+\w+/,
    /you\s+are\s+(diabetic|anemic|hypertensive|hyperthyroid|hypothyroid)/,
    /confirmed\s+(diabetes|anemia|thyroid|cancer|tumor|disease)/,
    /you\s+(definitely|clearly|certainly|surely)\s+have/,
    /this\s+is\s+(definitely|clearly|certainly)\s+(diabetes|cancer|anemia|thyroid)/,
    /no\s+doubt\s+(you\s+have|this\s+is|about)/,
    /100%\s+(sure|certain|confirmed)/,
    /without\s+(a\s+)?doubt/,
    /conclusive(ly)?\s+(shows?|proves?|indicates?)/,
  ]),

  // All medication patterns combined
  MEDICATION: combinePatterns([
    /take\s+\d+\s*(mg|ml|mcg|tablet|capsule|pill)/,
    /dosage[:\s]+\d+\s*(mg|ml|mcg)/,
    /prescri(be|ption|bed)[:\s]+/,
    /you\s+(should|must|need\s+to)\s+take\s+\w+\s+\d+/,
    /start\s+(taking|with)\s+\w+(in|ol|ide|ate|ine)\s+\d+/,
    /increase\s+(your\s+)?(dose|dosage|medication)/,
    /decrease\s+(your\s+)?(dose|dosage|medication)/,
    /stop\s+taking\s+\w+/,
    /switch\s+(to|from)\s+\w+/,
    /\d+\s*(mg|ml|mcg|g|iu)\s*(once|twice|thrice|daily|weekly|monthly)/,
    /\d+\s*times?\s*(a|per)\s*(day|week|month)/,
    /(morning|evening|night|before\s+meal|after\s+meal)\s*[:\-]?\s*\d+\s*(mg|tablet)/,
    /(take|try|use)\s+(paracetamol|aspirin|ibuprofen|crocin|dolo|combiflam)/,
  ]),

  // All dangerous patterns combined
  DANGEROUS: combinePatterns([
    /stop\s+(your\s+)?(medication|medicine|treatment|therapy)/,
    /don'?t\s+(see|visit|consult|go\s+to)\s+(a\s+)?(doctor|physician|hospital)/,
    /no\s+need\s+(to|for)\s+(see|visit|consult)\s+(a\s+)?doctor/,
    /you\s+don'?t\s+need\s+(a\s+)?doctor/,
    /ignore\s+(this|these|the)\s+(symptoms?|results?|values?)/,
    /nothing\s+to\s+worry\s+about/,
    /perfectly\s+(fine|normal|healthy)/,
    /cure\s+(diabetes|cancer|thyroid|hypertension)\s+(with|using|by)/,
    /home\s+remedy\s+(for|to\s+cure|to\s+treat)/,
    /(ayurvedic|homeopathic|natural)\s+(cure|treatment)\s+for/,
    /wait\s+(and\s+)?(see|watch)/,
    /give\s+it\s+(some\s+)?time/,
    /no\s+(immediate\s+)?action\s+(needed|required)/,
  ]),

  // All Hindi patterns combined
  HINDI: combinePatterns([
    /aapko\s+(diabetes|sugar|thyroid|bp|cancer)\s+hai/,
    /tumhe\s+(diabetes|sugar|thyroid|bp|cancer)\s+hai/,
    /ye\s+(diabetes|sugar|thyroid|bp)\s+(hai|he)/,
    /pakka\s+(diabetes|sugar|cancer|thyroid)/,
    /confirm\s+(diabetes|sugar|cancer|thyroid)/,
    /ye\s+(dawa|dawai|tablet|goli|medicine)\s+(lo|lena|khao|khana)/,
    /is\s+(tablet|goli|dawai)\s+se\s+(theek|thik|sahi)/,
    /(subah|sham|raat)\s+ko\s+\d+\s*(mg|tablet|goli)/,
    /din\s+me\s+\d+\s+(baar|time)\s+(lo|lena|khao)/,
    /\d+\s*(goli|tablet)\s+(roz|daily|rozana)/,
    /doctor\s+(ki\s+)?zaroorat\s+nahi/,
    /doctor\s+ke\s+paas\s+(mat\s+)?jana/,
    /tension\s+(mat\s+)?lo/,
    /kuch\s+nahi\s+(hoga|hua)/,
    /fikar\s+(mat\s+)?karo/,
    /chinta\s+(mat\s+)?karo/,
    /ghar\s+pe\s+(ilaj|treatment)/,
    /desi\s+(ilaj|nuskha|upay)/,
    /definitely\s+(sugar|diabetes|thyroid)\s+hai/,
    /100%\s+(sugar|diabetes|cancer)/,
    /pakka\s+wala\s+(disease|bimari)/,
  ]),
};

// 🔴 MASTER MEDICINE REGEX (All medicines in one pattern)
// 🔐 SECURITY: Using escapeRegex to prevent injection if list loaded from DB
export const COMPILED_MEDICINE_REGEX = new RegExp(
  `\\b(${BLOCKED_MEDICINE_NAMES.map(escapeRegex).join('|')})\\b`,
  'gi'
);

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 🔐 FUZZY MEDICINE DETECTION (Anti-Evasion v1.2)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Catches: "me tfor min", "met formin", "m€tformin", "m3tf0rmin"

// Common character substitutions used for evasion
const CHAR_SUBSTITUTIONS: Record<string, string[]> = {
  'a': ['a', '@', '4', 'α', 'а'],
  'e': ['e', '3', '€', 'ε', 'е'],
  'i': ['i', '1', '!', 'í', 'і'],
  'o': ['o', '0', 'ø', 'о'],
  's': ['s', '$', '5', 'ѕ'],
  't': ['t', '7', '+', 'т'],
  'l': ['l', '1', '|', 'і'],
  'n': ['n', 'η', 'и'],
};

// High-risk medicines that need fuzzy matching
const HIGH_RISK_MEDICINES = [
  'metformin', 'insulin', 'paracetamol', 'ibuprofen', 'aspirin',
  'amoxicillin', 'azithromycin', 'omeprazole', 'atorvastatin',
  'amlodipine', 'losartan', 'levothyroxine', 'alprazolam',
];

/**
 * Generate fuzzy regex pattern for a medicine name
 * Catches spacing tricks and character substitutions
 */
export const generateFuzzyMedicinePattern = (medicine: string): RegExp => {
  let pattern = '';
  
  for (const char of medicine.toLowerCase()) {
    const subs = CHAR_SUBSTITUTIONS[char];
    if (subs) {
      // Allow character OR substitutions OR optional space/special char
      pattern += `[${subs.join('')}\\s\\-\\_\\.]*`;
    } else {
      pattern += `[${char}\\s\\-\\_\\.]*`;
    }
  }
  
  return new RegExp(pattern, 'gi');
};

// Pre-compiled fuzzy patterns for high-risk medicines
export const FUZZY_MEDICINE_PATTERNS: Map<string, RegExp> = new Map(
  HIGH_RISK_MEDICINES.map(med => [med, generateFuzzyMedicinePattern(med)])
);

/**
 * Levenshtein distance for fuzzy matching
 * Returns similarity score (0-1, where 1 = exact match)
 */
export const calculateSimilarity = (str1: string, str2: string): number => {
  const s1 = str1.toLowerCase().replace(/[\s\-\_\.]/g, '');
  const s2 = str2.toLowerCase().replace(/[\s\-\_\.]/g, '');
  
  if (s1 === s2) return 1;
  if (s1.length === 0 || s2.length === 0) return 0;
  
  const matrix: number[][] = [];
  
  for (let i = 0; i <= s1.length; i++) {
    matrix[i] = [i];
  }
  for (let j = 0; j <= s2.length; j++) {
    matrix[0][j] = j;
  }
  
  for (let i = 1; i <= s1.length; i++) {
    for (let j = 1; j <= s2.length; j++) {
      const cost = s1[i - 1] === s2[j - 1] ? 0 : 1;
      matrix[i][j] = Math.min(
        matrix[i - 1][j] + 1,
        matrix[i][j - 1] + 1,
        matrix[i - 1][j - 1] + cost
      );
    }
  }
  
  const distance = matrix[s1.length][s2.length];
  const maxLength = Math.max(s1.length, s2.length);
  return 1 - distance / maxLength;
};

/**
 * Check if text contains fuzzy medicine matches
 * Returns detected medicines with confidence scores
 */
export const detectFuzzyMedicines = (text: string): Array<{
  medicine: string;
  matched: string;
  confidence: number;
  method: 'exact' | 'fuzzy' | 'levenshtein';
}> => {
  const results: Array<{
    medicine: string;
    matched: string;
    confidence: number;
    method: 'exact' | 'fuzzy' | 'levenshtein';
  }> = [];
  
  const normalizedText = text.toLowerCase();
  
  // Extract potential medicine-like words (4+ chars)
  const words = normalizedText.match(/\b[\w@$€4310!]+\b/g) || [];
  
  for (const medicine of HIGH_RISK_MEDICINES) {
    // Method 1: Fuzzy regex pattern matching
    const fuzzyPattern = FUZZY_MEDICINE_PATTERNS.get(medicine);
    if (fuzzyPattern) {
      fuzzyPattern.lastIndex = 0;
      const match = normalizedText.match(fuzzyPattern);
      if (match && match[0].replace(/[\s\-\_\.]/g, '').length >= medicine.length * 0.7) {
        results.push({
          medicine,
          matched: match[0],
          confidence: 0.85,
          method: 'fuzzy',
        });
        continue;
      }
    }
    
    // Method 2: Levenshtein distance for each word
    for (const word of words) {
      if (word.length >= medicine.length * 0.6) {
        const similarity = calculateSimilarity(word, medicine);
        if (similarity >= 0.75) { // 75% similarity threshold
          results.push({
            medicine,
            matched: word,
            confidence: similarity,
            method: 'levenshtein',
          });
          break;
        }
      }
    }
  }
  
  return results;
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 📋 TERMS ACCEPTANCE - ENFORCEMENT REQUIREMENTS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export interface HealthTermsAcceptance {
  userId: string;
  acceptedAt: Date;
  acceptedVersion: string;
  ipAddress: string;
  userAgent: string;
  disclaimerShown: boolean;
  explicitConsent: boolean;
  
  // v1.2: Additional legal requirements
  checkboxChecked: boolean;        // User ticked the checkbox
  scrolledToBottom: boolean;       // User scrolled through full terms
  timeSpentSeconds: number;        // Time spent on terms page (min 10s required)
  acknowledgedRisks: boolean;      // Acknowledged AI limitations
  consentRecordId: string;         // Unique ID for this consent record
}

export const CURRENT_TERMS_VERSION = '1.2.0';

// Minimum requirements for valid consent
export const TERMS_ACCEPTANCE_REQUIREMENTS = {
  MIN_TIME_SPENT_SECONDS: 10,      // Must spend at least 10 seconds
  MUST_SCROLL_TO_BOTTOM: true,     // Must scroll through full terms
  MUST_CHECK_CHECKBOX: true,       // Must explicitly check the box
  MUST_ACKNOWLEDGE_RISKS: true,    // Must acknowledge AI limitations
  VERSION_MUST_MATCH: true,        // Must accept current version
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 🎨 FRONTEND ENFORCEMENT CODE (Copy to Frontend)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/**
 * CRITICAL: This code MUST be implemented in frontend
 * Without this, legal protection is VOID
 * 
 * Copy this to your frontend HealthTermsModal component
 */
export const FRONTEND_TERMS_ENFORCEMENT = `
// ═══════════════════════════════════════════════════════════════════════════
// HEALTH TERMS MODAL - MANDATORY FRONTEND IMPLEMENTATION
// File: src/components/health/HealthTermsModal.tsx (or .jsx)
// ═══════════════════════════════════════════════════════════════════════════

import { useState, useEffect, useRef } from 'react';

interface TermsState {
  scrolledToBottom: boolean;
  checkboxChecked: boolean;
  acknowledgedRisks: boolean;
  timeSpent: number;
  canAccept: boolean;
}

export const HealthTermsModal = ({ 
  isOpen, 
  onAccept, 
  onDecline,
  userId 
}: {
  isOpen: boolean;
  onAccept: (consent: ConsentRecord) => void;
  onDecline: () => void;
  userId: string;
}) => {
  const [state, setState] = useState<TermsState>({
    scrolledToBottom: false,
    checkboxChecked: false,
    acknowledgedRisks: false,
    timeSpent: 0,
    canAccept: false,
  });
  
  const termsRef = useRef<HTMLDivElement>(null);
  const startTime = useRef<number>(Date.now());
  
  // Track time spent on modal
  useEffect(() => {
    if (!isOpen) return;
    
    startTime.current = Date.now();
    const interval = setInterval(() => {
      const elapsed = Math.floor((Date.now() - startTime.current) / 1000);
      setState(prev => ({ ...prev, timeSpent: elapsed }));
    }, 1000);
    
    return () => clearInterval(interval);
  }, [isOpen]);
  
  // Track scroll position
  const handleScroll = () => {
    if (!termsRef.current) return;
    
    const { scrollTop, scrollHeight, clientHeight } = termsRef.current;
    const scrolledToBottom = scrollTop + clientHeight >= scrollHeight - 50;
    
    if (scrolledToBottom && !state.scrolledToBottom) {
      setState(prev => ({ ...prev, scrolledToBottom: true }));
    }
  };
  
  // Check if all requirements met
  useEffect(() => {
    const canAccept = 
      state.scrolledToBottom &&
      state.checkboxChecked &&
      state.acknowledgedRisks &&
      state.timeSpent >= 10; // Minimum 10 seconds
    
    setState(prev => ({ ...prev, canAccept }));
  }, [state.scrolledToBottom, state.checkboxChecked, state.acknowledgedRisks, state.timeSpent]);
  
  const handleAccept = async () => {
    if (!state.canAccept) return;
    
    const consentRecord = {
      consentRecordId: crypto.randomUUID(),
      userId,
      acceptedAt: new Date().toISOString(),
      acceptedVersion: '1.2.0',
      ipAddress: '', // Filled by backend
      userAgent: navigator.userAgent,
      disclaimerShown: true,
      explicitConsent: true,
      checkboxChecked: state.checkboxChecked,
      scrolledToBottom: state.scrolledToBottom,
      timeSpentSeconds: state.timeSpent,
      acknowledgedRisks: state.acknowledgedRisks,
    };
    
    // Send to backend for storage
    await fetch('/api/v1/health/accept-terms', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(consentRecord),
    });
    
    onAccept(consentRecord);
  };
  
  if (!isOpen) return null;
  
  return (
    <div className="modal-overlay">
      <div className="terms-modal">
        <h2>⚠️ Soriva Health - Important Terms</h2>
        
        {/* Scrollable Terms Container */}
        <div 
          ref={termsRef}
          onScroll={handleScroll}
          className="terms-content"
          style={{ maxHeight: '400px', overflowY: 'scroll' }}
        >
          {/* Full terms content here */}
          <div dangerouslySetInnerHTML={{ __html: HEALTH_TERMS_HTML }} />
        </div>
        
        {/* Scroll indicator */}
        {!state.scrolledToBottom && (
          <p className="scroll-hint">
            ↓ Please scroll to read all terms ({state.timeSpent}s)
          </p>
        )}
        
        {/* Checkboxes - Only enabled after scrolling */}
        <div className="terms-checkboxes">
          <label className={!state.scrolledToBottom ? 'disabled' : ''}>
            <input
              type="checkbox"
              checked={state.checkboxChecked}
              onChange={(e) => setState(prev => ({ 
                ...prev, 
                checkboxChecked: e.target.checked 
              }))}
              disabled={!state.scrolledToBottom}
            />
            I have read and agree to the Terms of Service
          </label>
          
          <label className={!state.scrolledToBottom ? 'disabled' : ''}>
            <input
              type="checkbox"
              checked={state.acknowledgedRisks}
              onChange={(e) => setState(prev => ({ 
                ...prev, 
                acknowledgedRisks: e.target.checked 
              }))}
              disabled={!state.scrolledToBottom}
            />
            I understand that Soriva Health is NOT a substitute for 
            professional medical advice and I will consult a doctor 
            for all medical decisions
          </label>
        </div>
        
        {/* Buttons */}
        <div className="terms-buttons">
          <button onClick={onDecline} className="btn-decline">
            Decline
          </button>
          <button 
            onClick={handleAccept}
            disabled={!state.canAccept}
            className="btn-accept"
            title={!state.canAccept ? 
              'Please read terms and check both boxes' : 
              'Accept and continue'}
          >
            Accept & Continue
            {state.timeSpent < 10 && \` (\${10 - state.timeSpent}s)\`}
          </button>
        </div>
      </div>
    </div>
  );
};

// Terms HTML content
const HEALTH_TERMS_HTML = \`
<h3>Soriva Health - Terms of Service</h3>

<p><strong>Effective Date:</strong> November 2024</p>
<p><strong>Version:</strong> 1.2.0</p>

<h4>1. IMPORTANT DISCLAIMER</h4>
<p>Soriva Health is an AI-powered health information tool. 
It is <strong>NOT</strong> a medical service, and does <strong>NOT</strong> 
provide medical advice, diagnosis, or treatment recommendations.</p>

<h4>2. LIMITATIONS OF AI</h4>
<ul>
  <li>AI can make errors in interpreting health data</li>
  <li>AI cannot replace physical examination by a doctor</li>
  <li>AI does not have access to your complete medical history</li>
  <li>AI cannot prescribe medications or treatments</li>
</ul>

<h4>3. YOUR RESPONSIBILITIES</h4>
<ul>
  <li>Always consult a qualified healthcare provider for medical decisions</li>
  <li>Do not delay seeking medical care based on AI information</li>
  <li>In case of emergency, call emergency services immediately</li>
  <li>Verify all AI-generated information with your doctor</li>
</ul>

<h4>4. LIABILITY</h4>
<p>Soriva and its creators are <strong>NOT LIABLE</strong> for any 
decisions made based on information provided by this service. 
You use this service at your own risk.</p>

<h4>5. DATA PRIVACY</h4>
<p>Your health data is encrypted and stored securely. 
You can request deletion of your data at any time.</p>

<h4>6. EMERGENCY SITUATIONS</h4>
<p>If you are experiencing a medical emergency, 
<strong>DO NOT</strong> use this app. Call emergency services:</p>
<ul>
  <li>India: 108 / 112</li>
  <li>USA: 911</li>
</ul>
\`;
`;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 🔒 BACKEND TERMS VALIDATION
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/**
 * Validate consent record from frontend
 * Call this in your /api/v1/health/accept-terms endpoint
 */
export const validateTermsAcceptance = (
  consent: HealthTermsAcceptance
): { valid: boolean; errors: string[] } => {
  const errors: string[] = [];

  // Check version
  if (consent.acceptedVersion !== CURRENT_TERMS_VERSION) {
    errors.push(`Invalid terms version. Expected ${CURRENT_TERMS_VERSION}`);
  }

  // Check time spent
  if (consent.timeSpentSeconds < TERMS_ACCEPTANCE_REQUIREMENTS.MIN_TIME_SPENT_SECONDS) {
    errors.push(`Insufficient time spent on terms. Minimum ${TERMS_ACCEPTANCE_REQUIREMENTS.MIN_TIME_SPENT_SECONDS}s required`);
  }

  // Check scroll
  if (TERMS_ACCEPTANCE_REQUIREMENTS.MUST_SCROLL_TO_BOTTOM && !consent.scrolledToBottom) {
    errors.push('User must scroll through entire terms');
  }

  // Check checkbox
  if (TERMS_ACCEPTANCE_REQUIREMENTS.MUST_CHECK_CHECKBOX && !consent.checkboxChecked) {
    errors.push('User must check the acceptance checkbox');
  }

  // Check risk acknowledgment
  if (TERMS_ACCEPTANCE_REQUIREMENTS.MUST_ACKNOWLEDGE_RISKS && !consent.acknowledgedRisks) {
    errors.push('User must acknowledge AI limitations');
  }

  // Check explicit consent
  if (!consent.explicitConsent) {
    errors.push('Explicit consent not provided');
  }

  return {
    valid: errors.length === 0,
    errors,
  };
};

/**
 * Check if user has valid terms acceptance
 * Call this BEFORE any health API request
 */
export const checkUserTermsStatus = async (
  userId: string,
  prisma: any
): Promise<{ accepted: boolean; needsReaccept: boolean; reason?: string }> => {
  const acceptance = await prisma.healthTermsAcceptance.findUnique({
    where: { userId },
  });

  if (!acceptance) {
    return { accepted: false, needsReaccept: true, reason: 'No terms acceptance record' };
  }

  // Check if version is current
  if (acceptance.acceptedVersion !== CURRENT_TERMS_VERSION) {
    return { 
      accepted: false, 
      needsReaccept: true, 
      reason: `Terms updated. Please accept version ${CURRENT_TERMS_VERSION}` 
    };
  }

  // Check if acceptance was valid
  const validation = validateTermsAcceptance(acceptance);
  if (!validation.valid) {
    return { 
      accepted: false, 
      needsReaccept: true, 
      reason: validation.errors[0] 
    };
  }

  return { accepted: true, needsReaccept: false };
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 🚨 CRITICAL: HEALTH TERMS MIDDLEWARE (MUST USE IN ALL HEALTH ROUTES)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ⚠️ WITHOUT THIS MIDDLEWARE, ENTIRE CONSENT SYSTEM HAS ZERO LEGAL VALUE
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/**
 * Express middleware to enforce terms acceptance
 * 
 * USAGE (MANDATORY):
 * 
 * // In health.routes.ts
 * import { healthTermsMiddleware } from './health.constants';
 * 
 * router.use('/api/v1/health', healthTermsMiddleware);
 * 
 * // OR for specific routes
 * router.post('/reports', healthTermsMiddleware, uploadReport);
 * router.post('/chat', healthTermsMiddleware, healthChat);
 */
export const HEALTH_TERMS_MIDDLEWARE_CODE = `
// ═══════════════════════════════════════════════════════════════════════════
// HEALTH TERMS MIDDLEWARE - COPY TO: src/modules/health/health.middleware.ts
// ═══════════════════════════════════════════════════════════════════════════
// 🚨 THIS IS LEGALLY REQUIRED - DO NOT SKIP
// ═══════════════════════════════════════════════════════════════════════════

import { Request, Response, NextFunction } from 'express';
import { PrismaClient } from '@prisma/client';
import { 
  checkUserTermsStatus, 
  CURRENT_TERMS_VERSION,
  HEALTH_DISCLAIMER 
} from './health.constants';

const prisma = new PrismaClient();

// Routes that DON'T require terms (allow viewing terms page)
const EXEMPT_ROUTES = [
  '/api/v1/health/terms',           // View terms
  '/api/v1/health/accept-terms',    // Accept terms
  '/api/v1/health/terms-status',    // Check status
];

/**
 * 🚨 CRITICAL MIDDLEWARE - Enforces terms acceptance
 * 
 * This middleware MUST be applied to ALL health routes.
 * Without this, the consent system has ZERO legal value.
 */
export const healthTermsMiddleware = async (
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> => {
  try {
    // Skip exempt routes
    if (EXEMPT_ROUTES.some(route => req.path.startsWith(route))) {
      return next();
    }

    // Get user ID from auth (adjust based on your auth system)
    const userId = (req as any).user?.id;
    
    if (!userId) {
      res.status(401).json({
        success: false,
        error: 'Authentication required',
        code: 'AUTH_REQUIRED',
      });
      return;
    }

    // Check terms acceptance status
    const termsStatus = await checkUserTermsStatus(userId, prisma);

    // 🚨 HARD BLOCK - No terms = No access
    if (!termsStatus.accepted) {
      res.status(403).json({
        success: false,
        error: 'Terms acceptance required',
        code: 'TERMS_REQUIRED',
        requiresConsent: true,
        reason: termsStatus.reason,
        currentVersion: CURRENT_TERMS_VERSION,
        action: {
          type: 'SHOW_TERMS_MODAL',
          endpoint: '/api/v1/health/terms',
          acceptEndpoint: '/api/v1/health/accept-terms',
        },
        disclaimer: HEALTH_DISCLAIMER.SHORT,
      });
      return;
    }

    // Terms accepted - proceed
    next();
  } catch (error) {
    console.error('Health terms middleware error:', error);
    
    // On error, fail CLOSED (block access) for safety
    res.status(500).json({
      success: false,
      error: 'Unable to verify terms acceptance',
      code: 'TERMS_CHECK_FAILED',
      requiresConsent: true,
    });
  }
};

/**
 * Audit log for terms-related actions
 */
export const logTermsAction = async (
  userId: string,
  action: 'ACCEPTED' | 'DECLINED' | 'BLOCKED' | 'EXPIRED',
  metadata: Record<string, any>
): Promise<void> => {
  try {
    await prisma.healthTermsAuditLog.create({
      data: {
        userId,
        action,
        version: CURRENT_TERMS_VERSION,
        metadata: JSON.stringify(metadata),
        ipAddress: metadata.ipAddress || 'unknown',
        userAgent: metadata.userAgent || 'unknown',
        timestamp: new Date(),
      },
    });
  } catch (error) {
    console.error('Failed to log terms action:', error);
  }
};
`;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 📋 HEALTH ROUTES SETUP (COPY TO YOUR ROUTES FILE)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const HEALTH_ROUTES_SETUP_CODE = `
// ═══════════════════════════════════════════════════════════════════════════
// HEALTH ROUTES - COPY TO: src/modules/health/health.routes.ts
// ═══════════════════════════════════════════════════════════════════════════

import { Router } from 'express';
import { healthTermsMiddleware } from './health.middleware';
import { HealthController } from './health.controller';

const router = Router();
const controller = new HealthController();

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 🔓 PUBLIC ROUTES (No terms required)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// Get terms content
router.get('/terms', controller.getTerms);

// Accept terms
router.post('/accept-terms', controller.acceptTerms);

// Check terms status
router.get('/terms-status', controller.getTermsStatus);

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 🔒 PROTECTED ROUTES (Terms REQUIRED)
// 🚨 healthTermsMiddleware MUST be applied here
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// Apply middleware to ALL protected routes
router.use(healthTermsMiddleware);

// Reports
router.post('/reports/upload', controller.uploadReport);
router.get('/reports', controller.getReports);
router.get('/reports/:id', controller.getReport);
router.delete('/reports/:id', controller.deleteReport);

// Analysis
router.post('/reports/:id/analyze', controller.analyzeReport);

// Chat
router.post('/chat', controller.healthChat);
router.get('/chat/history', controller.getChatHistory);

// Compare
router.post('/compare', controller.compareReports);

// Summary
router.post('/summary', controller.generateSummary);

// Alerts
router.get('/alerts', controller.getAlerts);
router.patch('/alerts/:id/read', controller.markAlertRead);

// Stats & Usage
router.get('/stats', controller.getStats);
router.get('/usage', controller.getUsage);

// Family (for FAMILY plan)
router.get('/family', controller.getFamilyMembers);
router.post('/family', controller.addFamilyMember);
router.delete('/family/:id', controller.removeFamilyMember);

// Emergency
router.get('/emergency/contacts', controller.getEmergencyContacts);
router.post('/emergency/contacts', controller.addEmergencyContact);

export default router;
`;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 📊 PRISMA SCHEMA ADDITIONS (Add to schema.prisma)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const PRISMA_SCHEMA_ADDITIONS = `
// ═══════════════════════════════════════════════════════════════════════════
// ADD TO: prisma/schema.prisma
// ═══════════════════════════════════════════════════════════════════════════

// Health Terms Acceptance Record
model HealthTermsAcceptance {
  id              String   @id @default(cuid())
  userId          String   @unique
  
  // Acceptance details
  acceptedAt      DateTime @default(now())
  acceptedVersion String
  
  // Legal requirements
  checkboxChecked    Boolean
  scrolledToBottom   Boolean
  timeSpentSeconds   Int
  acknowledgedRisks  Boolean
  explicitConsent    Boolean
  disclaimerShown    Boolean
  
  // Tracking
  consentRecordId String   @unique
  ipAddress       String
  userAgent       String
  
  // Timestamps
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  
  // Relation
  user User @relation(fields: [userId], references: [id], onDelete: Cascade)
  
  @@index([userId])
  @@index([acceptedVersion])
  @@map("health_terms_acceptance")
}

// Health Terms Audit Log (for legal compliance)
model HealthTermsAuditLog {
  id        String   @id @default(cuid())
  userId    String
  action    String   // ACCEPTED, DECLINED, BLOCKED, EXPIRED
  version   String
  metadata  String?  @db.Text
  ipAddress String
  userAgent String
  timestamp DateTime @default(now())
  
  @@index([userId])
  @@index([action])
  @@index([timestamp])
  @@map("health_terms_audit_log")
}
`;

